#
# EcoCrates
# by Auxilor
#

keygui:
  rows: 3
  mask:
    items:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "110101011"
      - "111111111"
  title: "Your Keys"

animations:
  spiral:
    spirals-per-second: 0.5
    rises-per-second: 0.25
    radius: 1.5
    height: 1
  double_spiral:
    spirals-per-second: 0.25
    rises-per-second: 0.125
    radius: 1.5
    height: 1
  circle:
    spirals-per-second: 0.5
    radius: 1.5
    height: 1

rolls:
  csgo:
    filler: black_stained_glass_pane name:""
    selector: lime_stained_glass_pane name:""
    bias: 0.65
    scrolls: 35
    max-delay: 25
