#
# EcoCrates
# by Auxilor
#

no-key-velocity: 1.5 # The speed at which a player should be launched away from a crate if they try to open it without a key. Set to 0 to disable.

reroll:
  rows: 3
  mask:
    items:
      - black_stained_glass_pane
      - green_stained_glass_pane
    pattern:
      - "122211111"
      - "120211011"
      - "122211111"
  title: "Accept your reward?"
  accept:
    row: 2
    column: 3
  reroll:
    row: 2
    column: 7
    item: orange_stained_glass_pane
    name: "&6Reroll"
    lore:
      - "&fNot happy with your item?"
      - "&fClick to try again for"
      - "&fa chance at something else!"
      - ""
      - "&cYou can only reroll once!"

keygui:
  rows: 3
  mask:
    items:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "110101011"
      - "111111111"
  title: "Your Keys"

animations:
  spiral:
    spirals-per-second: 0.5
    rises-per-second: 0.25
    radius: 1.5
    height: 1
  double_spiral:
    spirals-per-second: 0.25
    rises-per-second: 0.125
    radius: 1.5
    height: 1
  circle:
    spirals-per-second: 0.5
    radius: 1.5
    height: 1
  twirl:
    spirals-per-second: 0.5
    ticks: 80
    small-radius: 0.2
    large-radius: 1.2
    start-height: 2
    end-height: 0.7

rolls:
  csgo:
    filler: black_stained_glass_pane name:""
    selector: lime_stained_glass_pane name:""
    bias: 0.65
    scrolls: 35
    max-delay: 25
  flash:
    duration: 80
    wait: 20
  encircle:
    spin-time: 100
    reveal-time: 80
    items: 12
    radius: 3
    height: 1
    spins-per-second: 0.5
    rise-velocity: 0.05
    spin-velocity: 0.4
    reveal-velocity: 0.2
  quick:
    height: 1.5
    rise-velocity: 0.05
    suspend: 10